"""Shared Azure geography group labels for regional rollout context."""

from __future__ import annotations

REGION_GROUPS: dict[str, str] = {
    "australiaeast": "Oceania",
    "australiacentral": "Oceania",
    "australiacentral2": "Oceania",
    "australiasoutheast": "Oceania",
    "newzealandnorth": "Oceania",
    "austriaeast": "Europe",
    "belgiumcentral": "Europe",
    "denmarkeast": "Europe",
    "francecentral": "Europe",
    "francesouth": "Europe",
    "germanynorth": "Europe",
    "germanywestcentral": "Europe",
    "italynorth": "Europe",
    "northeurope": "Europe",
    "norwayeast": "Europe",
    "norwaywest": "Europe",
    "polandcentral": "Europe",
    "spaincentral": "Europe",
    "swedencentral": "Europe",
    "switzerlandnorth": "Europe",
    "switzerlandwest": "Europe",
    "uksouth": "Europe",
    "ukwest": "Europe",
    "westeurope": "Europe",
    "brazilsouth": "South America",
    "brazilsoutheast": "South America",
    "chilecentral": "South America",
    "canadacentral": "North America",
    "canadaeast": "North America",
    "centralus": "North America",
    "centraluseuap": "North America",
    "eastus": "North America",
    "eastus2": "North America",
    "eastus2euap": "North America",
    "eastusstg": "North America",
    "mexicocentral": "North America",
    "northcentralus": "North America",
    "southcentralus": "North America",
    "southcentralusstg": "North America",
    "westcentralus": "North America",
    "westus": "North America",
    "westus2": "North America",
    "westus3": "North America",
    "centralindia": "Asia",
    "eastasia": "Asia",
    "indonesiacentral": "Asia",
    "japaneast": "Asia",
    "japanwest": "Asia",
    "jioindiacentral": "Asia",
    "jioindiawest": "Asia",
    "koreacentral": "Asia",
    "koreasouth": "Asia",
    "malaysiawest": "Asia",
    "southindia": "Asia",
    "southeastasia": "Asia",
    "westindia": "Asia",
    "israelcentral": "Middle East",
    "qatarcentral": "Middle East",
    "uaecentral": "Middle East",
    "uaenorth": "Middle East",
    "southafricanorth": "Africa",
    "southafricawest": "Africa",
}


def region_group(region: str) -> str | None:
    return REGION_GROUPS.get(region.lower().replace(" ", ""))
